// Builds tests/inpage/contract-check.js = contract.js + inpage/checker.src.js,
// so the in-page checker is one self-contained paste.
const fs = require("fs");
const path = require("path");
const root = path.resolve(__dirname, "..");
const contract = fs.readFileSync(path.join(root, "contract.js"), "utf8");
const checker = fs.readFileSync(path.join(__dirname, "inpage", "checker.src.js"), "utf8");
const out = `// GENERATED by tests/build-inpage.js — do not edit; edit contract.js and inpage/checker.src.js.\n${contract}\n${checker}`;
fs.writeFileSync(path.join(__dirname, "inpage", "contract-check.js"), out);
console.log("wrote tests/inpage/contract-check.js", out.length, "bytes");
